include everforest.conf

enable_audio_bell no

font_family JetBrainsMono Nerd Font
font_size 14.0

U+3000-U+303F Noto Sans CJK JP
U+3040-U+309F Noto Sans CJK JP
U+30A0-U+30FF Noto Sans CJK JP
U+4E00-U+9FFF Noto Sans CJK JP
U+FF00-U+FFEF Noto Sans CJK JP
