# Settings for NVIDIA
# xrandr --setprovideroutputsource modesetting NVIDIA-0
# xrandr --auto

export DOTFILES=$HOME/dotfiles

flatpak override --user --reset-all io.github.zen_browser.Zen

# Start picom for compositing
picom &

# Start my notification centre
dunst &

# Start the i3 window manager
exec i3
