#!/bin/sh

# Based on AUR i3lock-color package

BLANK='#00000000'
CLEAR='#29313622'
DEFAULT='#3A464Cff'
FOREGROUND='#555F66ff'
TEXT='#DBBC7Fff'
DATE='#A7C08088'
BGDIM='#29313666'
INPUT='#A7C080ff'
WRONG='#E67E80bb'
VERIFYING='#7FBBB3ff'
FONT='JetBrainsMono Nerd Font Regular'

i3lock \
--insidever-color=$BGDIM         \
--ringver-color=$VERIFYING       \
\
--insidewrong-color=$BGDIM       \
--ringwrong-color=$WRONG         \
\
--inside-color=$BGDIM            \
--ring-color=$DEFAULT            \
--line-color=$BLANK              \
--separator-color=$DEFAULT       \
\
--verif-color=$VERIFYING         \
--wrong-color=$WRONG             \
--time-color=$INPUT              \
--date-color=$DATE     \
--layout-color=$FOREGROUND       \
--keyhl-color=$INPUT             \
--bshl-color=$WRONG              \
\
--screen 1                       \
--blur 9                         \
--clock                          \
--indicator                      \
--radius=100                     \
--time-str="%H:%M:%S"            \
--date-str="%A, %d-%m-%Y"        \
--wrong-text="Wrong!"    \
--verif-text="checking..."       \
--keylayout 1                    \
--date-font=$FONT                \
--wrong-font=$FONT               \
--layout-font=$FONT              \
